"""Corpus statistics for the dataset section (writes docs/dataset-stats.md).

Pure local computation over data/*/graphs and data/*/raw — no network, no
model calls. Run after any corpus change:

    uv run --native-tls python scripts/corpus_stats.py
"""

from __future__ import annotations

import json
import statistics
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / 'src'))

from graph_bench.oncall_graph.models import Task  # noqa: E402

DOMAIN = {
    'bugzilla.mozilla.org': 'Mozilla (non-UI)',
    'postgresql.org': 'databases',
    'moby': 'systems/networking',
    'curl': 'systems/networking',
    'traefik': 'systems/networking',
    'containerd': 'systems/networking',
    'etcd-io': 'systems/networking',
    'duckdb': 'databases',
    'ClickHouse': 'databases',
    'vllm-project': 'ML/inference',
    'ollama': 'ML/inference',
    'ggml-org': 'ML/inference',
    'pytorch': 'ML/inference',
    'flutter': 'web frameworks',
    'expo': 'web frameworks',
    'denoland': 'language runtimes',
    'nodejs': 'language runtimes',
    'python': 'language runtimes',
    'micropython': 'IoT/home automation',
    'home-assistant': 'IoT/home automation',
}


def domain_of(repo: str, slug: str = '') -> str:
    for key, dom in DOMAIN.items():
        if repo.startswith(key):
            return dom
    # Hand-piloted Bugzilla raws are bare REST dumps with no 'repo' field.
    if slug.startswith('bmo'):
        return 'Mozilla (non-UI)'
    return 'other'


def _fmt(values: list[float]) -> str:
    if not values:
        return '—'
    return (
        f'{statistics.mean(values):.1f} '
        f'(median {statistics.median(values):.0f}, '
        f'{min(values):.0f}–{max(values):.0f})'
    )


def main() -> int:
    rows = []
    held_back = 0
    for gp in sorted(REPO.glob('data/*/graphs/*.json')):
        slug = gp.stem
        src = gp.parents[1].name
        raw_path = REPO / f'data/{src}/raw/{slug}.json'
        raw = json.loads(raw_path.read_text()) if raw_path.exists() else {}
        task = Task.model_validate_json(gp.read_text())
        # The repository ships every drafted graph, including the ones the
        # two-stage review blocked. `metadata.hitl_reviewed` is what marks
        # the released set — the only set any published number describes —
        # so the statistics must filter on it, not on what is on disk.
        if not (task.metadata and task.metadata.hitl_reviewed):
            held_back += 1
            continue
        g = task.graph
        clar = [c for e in g.edges for c in e.clarifications]
        sols = [e.solution for e in g.edges if e.solution is not None]
        n_msgs = 1 + len(raw.get('comments', []))
        if not n_msgs and raw.get('comments') is None:
            n_msgs = 0
        levels = Counter(c.level for c in clar if c.level)
        rows.append({
            'slug': slug,
            'source': src,
            'repo': raw.get('repo', ''),
            'domain': domain_of(raw.get('repo', ''), slug),
            'created': (raw.get('created_at') or '')[:10],
            'msgs': n_msgs,
            'participants': len({c.get('author') for c in raw.get('comments', [])}) + 1,
            'nodes': len(g.nodes),
            'edges': len(g.edges),
            'clarifications': len(clar),
            'solutions': len(sols),
            'blind': sum(1 for s in sols if s.is_known_blind_path),
            'shortcuts': sum(1 for s in sols if s.is_shortcut),
            'counterfactuals': sum(
                len(c.counterfactual_candidates) for c in clar
            ),
            'images': len(task.opening_images)
            + sum(len(n.symptom_images) for n in g.nodes.values())
            + sum(len(c.images) for c in clar),
            'sat_conditions': len(task.satisfaction_conditions),
            'L1': levels.get('L1_basic', 0),
            'L2': levels.get('L2_inferable', 0),
            'L3': levels.get('L3_specific', 0),
            'signed': bool(task.metadata.hitl_reviewed),
            'snapshot': bool(task.metadata.repo_snapshot),
        })

    n = len(rows)
    by_domain = Counter(r['domain'] for r in rows)
    by_source = Counter(r['source'] for r in rows)
    years = Counter(r['created'][:4] for r in rows if r['created'])

    def col(k: str) -> list[float]:
        return [float(r[k]) for r in rows]

    lines = [
        '# Corpus statistics',
        '',
        f'Generated by `scripts/corpus_stats.py` over the {n} released '
        f'task graphs (corpus v2.1, `metadata.hitl_reviewed: true`). '
        f'{held_back} further drafts ship alongside them but are held back '
        f'by review — see `docs/corpus-v2.md` and `data/REVIEW_FINDINGS.json`.',
        '',
        '## Coverage',
        '',
        '| Domain | Cases | Repositories |',
        '|---|---|---|',
    ]
    for dom, cnt in by_domain.most_common():
        repos = sorted(
            {
                (r['repo'].split('/')[-1] or 'bugzilla.mozilla.org')
                for r in rows
                if r['domain'] == dom
            }
        )
        lines.append(f'| {dom} | {cnt} | {", ".join(repos)} |')
    lines += [
        f'| **total** | **{n}** | |',
        '',
        f'Sources: '
        + ', '.join(f'{k} {v}' for k, v in sorted(by_source.items()))
        + '.',
        '',
        'Issue-creation years: '
        + ', '.join(f'{y} ({c})' for y, c in sorted(years.items()))
        + '.',
        '',
        '## Thread and graph size',
        '',
        '| Quantity | Mean (median, range) |',
        '|---|---|',
        f'| source messages per thread | {_fmt(col("msgs"))} |',
        f'| distinct participants | {_fmt(col("participants"))} |',
        f'| nodes | {_fmt(col("nodes"))} |',
        f'| edges | {_fmt(col("edges"))} |',
        f'| clarifications | {_fmt(col("clarifications"))} |',
        f'| solution edges | {_fmt(col("solutions"))} |',
        f'| known-blind paths | {_fmt(col("blind"))} |',
        f'| counterfactual variants | {_fmt(col("counterfactuals"))} |',
        f'| satisfaction conditions | {_fmt(col("sat_conditions"))} |',
        '',
        '## Elicitation difficulty (information levels)',
        '',
        '| Level | Clarifications | Share |',
        '|---|---|---|',
    ]
    tot_l = sum(sum(r[k] for r in rows) for k in ('L1', 'L2', 'L3')) or 1
    for lvl, label in (
        ('L1', 'L1 — any user states it unprompted'),
        ('L2', 'L2 — inferable from surfaced evidence'),
        ('L3', 'L3 — must be asked for or measured'),
    ):
        c = sum(r[lvl] for r in rows)
        lines.append(f'| {label} | {c} | {100 * c / tot_l:.0f}% |')

    n_blind = sum(1 for r in rows if r['blind'])
    n_short = sum(1 for r in rows if r['shortcuts'])
    n_img = sum(1 for r in rows if r['images'])
    lines += [
        '',
        '## Structural features',
        '',
        f'- {n_blind}/{n} cases contain at least one thread-falsified '
        f'(known-blind) attempt; {sum(r["blind"] for r in rows)} blind edges '
        f'in total.',
        f'- {n_short}/{n} cases carry a shortcut edge (the correct answer '
        f'reachable without the full evidence chain).',
        f'- {n_img}/{n} cases attach original screenshots '
        f'({sum(r["images"] for r in rows)} images hooked to the exact node '
        f'or clarification they evidence).',
        f'- {sum(r["snapshot"] for r in rows)}/{n} carry a repo snapshot '
        f'(default-branch commit at issue-creation time) for the '
        f'repo-grounded track.',
        f'- {sum(r["signed"] for r in rows)}/{n} passed release sign-off.',
        '',
        '## Per-case table',
        '',
        '| case | domain | msgs | nodes | edges | clar | blind | L1/L2/L3 |',
        '|---|---|---|---|---|---|---|---|',
    ]
    for r in sorted(rows, key=lambda r: (r['domain'], r['slug'])):
        lines.append(
            f'| {r["slug"]} | {r["domain"]} | {r["msgs"]} | {r["nodes"]} | '
            f'{r["edges"]} | {r["clarifications"]} | {r["blind"]} | '
            f'{r["L1"]}/{r["L2"]}/{r["L3"]} |'
        )

    out = REPO / 'docs' / 'dataset-stats.md'
    out.write_text('\n'.join(lines) + '\n')
    (REPO / 'data' / 'corpus_stats.json').write_text(
        json.dumps(rows, ensure_ascii=False, indent=1)
    )
    print(f'wrote {out} and data/corpus_stats.json ({n} cases)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
